import cx_Oracle
con=cx_Oracle.connect('ankit123/ankit')
cur=con.cursor()
#signup
cur.execute("""CREATE TABLE REGISTRATION(
        ACCOUNT_NUMBER NUMBER(10) PRIMARY KEY,
        FULL_NAME VARCHAR2(20),
        CONTACT_NO NUMBER(10),
        EMAIL_ID VARCHAR2(30),
        PASSWORD VARCHAR2(20),
        ADDRESS VARCHAR2(50))""")
#savings account
cur.execute("""CREATE TABLE NEW_USER(
        CUST_ID NUMBER(5) PRIMARY KEY,
        ACCOUNT_NUMBER NUMBER(10) REFERENCES REGISTRATION(ACCOUNT_NUMBER),
        ACCOUNT_BALANCE NUMBER(12,2))""")
##current account
cur.execute("""CREATE TABLE NEW_USER1(
        CUST_ID NUMBER(5) PRIMARY KEY,
        ACCOUNT_NUMBER NUMBER(10) REFERENCES REGISTRATION(ACCOUNT_NUMBER),
        ACCOUNT_BALANCE NUMBER(12,2))""")
##fixed deposit account
cur.execute("""CREATE TABLE FIXED_DEPOSIT(
        CUST_ID NUMBER(5),
        ACCOUNT_NUMBER NUMBER(10) REFERENCES REGISTRATION(ACCOUNT_NUMBER),
        TERM NUMBER(2),
        ACCOUNT_BALANCE NUMBER(12,2))""")
#administrator
cur.execute("""CREATE TABLE NEW_ADMIN(
        ADMIN_ID NUMBER(5) PRIMARY KEY,
        FULL_NAME VARCHAR2(20),
        CONTACT_NO NUMBER(10),
        EMAIL_ID VARCHAR2(30),
        PASSWORD VARCHAR2(20),
        ADDRESS VARCHAR2(50))""")
#closed accounts
cur.execute("""CREATE TABLE CLOSED_ACCOUNTS(
        CUST_ID NUMBER(5) PRIMARY KEY,
        ACCOUNT_NUMBER NUMBER(10),
        ACCOUNT_BALANCE(12,2))
        DATE_CLOSED DATE""")
#transactions 
cur.execute("""CREATE TABLE TRANSACTIONS(
ACCOUNT_NUMBER NUMBER(10),
DATE_OF_TRANSACTION DATE,
TRANSACTION_TYPE VARCHAR2(6),
AMOUNT NUMBER(12,2),
ACCOUNT_BALANCE NUMBER(12,2))""")
#loan
cur.execute("""CREATE TABLE LOAN(
CUST_ID NUMBER(5),
ACCOUNT_NUMBER NUMBER(10) REFERENCES REGISTRATION(ACCOUNT_NUMBER),
LOAN_AMOUNT NUMBER(12,2),
REPAYMENT_TERM NUMBER(2))""")
con.commit()
con.close()
